apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.passwordSecret.name }}
  namespace: {{ .Values.global.namespace.backup }}
  labels:
    app: postgresql
type: Opaque
data:
  {{ .Values.database.passwordSecret.key }}: {{ .Values.database.password | b64enc }}