apiVersion: backup.csyeteam03.xyz/v1
kind: BackupDatabaseSchema
metadata:
  name: {{ .Values.backup.name }}
  namespace: {{ .Values.global.namespace.backup }}
  labels:
    {{- include "dbOperator.labels" . | nindent 4 }}
spec:
  dbHost: {{ .Values.database.host | quote }}
  dbUser: {{ .Values.database.user | quote }}
  dbPasswordSecretName: {{ .Values.database.passwordSecret.name | quote }}
  dbPasswordSecretNamespace: {{ .Values.global.namespace.backup | quote }}
  dbPasswordSecretKey: {{ .Values.database.passwordSecret.key | quote }}
  dbName: {{ .Values.database.name | quote }}
  dbSchema: {{ .Values.database.schema | quote }}
  dbPort: {{ .Values.database.port }}
  gcsBucket: {{ .Values.gcs.bucket | quote }}
  kubeServiceAccount: {{ .Values.serviceAccount.backup.name | quote }}
  gcpServiceAccount: {{ .Values.serviceAccount.backup.gcpServiceAccount | quote }}
  backupJobNamespace: {{ .Values.global.namespace.backup | quote }}