apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: db-operator-sa
    namespace: operator-ns
roleRef:
  kind: ClusterRole
  name: backup-operator-role
  apiGroup: rbac.authorization.k8s.io